version: '3.7'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 4096
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - logging
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: kibana:6.5.4
    environment:
      - "XPACK_MONITORING_ENABLED=false"
    networks:
      - logging
    ports:
      - "5601:5601"
    restart: always

volumes:
  es-data: {}

networks:
  logging: {}
